import './globals.css'
import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'
import BackToHome from "@/app/component/BackToHome";

export const metadata : Metadata = {
  title: 'Tourlist',
  description: 'Generated by create next app',
}

const font = Montserrat({
  subsets: ['latin']
})

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
      {children}
      </body>
    </html>
  )
}
